### ISSUE TITLE
Tab visibility not working

### ISSUE THREAD

**Issue by SimonB1969** [bsgriggs/mendix-controllable-tab-container#1]
Hi, 

Trying to set dynamic visibility of tabs using parameters but doesn't appear to work. Even setting visibility explicitly to 'false' and tab still visible. This is on Mendix 9.18.2

Does give us dynamic control of default tab though so really useful in that respect!

**Comment by bsgriggs** [comment]
Hi,

Can you please add some screenshots of your configuration, so I can better understand the issue?

**Comment by bsgriggs** [comment]
Issue fixed and updated to the marketplace as v1.1 https://marketplace.mendix.com/link/component/204124

**Comment by SimonB1969** [comment]
Thanks Ben, can confirm the fix has worked. Many thanks for sorting for us.


From: Benjamin Griggs ***@***.***>
Date: Monday, 6 March 2023 at 14:42
To: bsgriggs/mendix-controllable-tab-container ***@***.***>
Cc: Simon Belsten ***@***.***>, Author ***@***.***>
Subject: Re: [bsgriggs/mendix-controllable-tab-container] Tab visibility not working (Issue #1)

Issue fixed and updated to the marketplace as v1.1 https://marketplace.mendix.com/link/component/204124
