### ISSUE TITLE
Tab page visibility based on module roles

### ISSUE THREAD

**Issue by YvdG** [bsgriggs/mendix-controllable-tab-container#3]
Thanks for this very useful widget!

An extra feature I would love to see is a visibility property based on module roles, so that you can show or hide each tab based on the role.

See the regular Tab container for an example:
![image](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/147413508/c84cb3f3-c31d-447a-8c44-8fe32b3983df)

**Comment by bsgriggs** [comment]
Hello,

Unfortunately, this isn't something supported by the Pluggable Widget API, so I cannot add it. As a workaround, you could use a non-persistent helper object with an enum for each user role you need. 

![Screenshot 2023-10-09 at 10 42 11 AM](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/47681665/b70784b8-2521-470d-84e6-821f4c4434b9)

The data source that provides the helper can set the boolean based on the highest role of the user. Then in the widget, you set the visibility condition based on the helper's enum value.

![Screenshot 2023-10-09 at 10 43 24 AM](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/47681665/21e596f0-5fbd-45ae-80e7-24399265d129)

**Comment by YvdG** [comment]
Thanks for your quick reply and detailed description of a workaround.
I'll try your suggestion.
