### ISSUE TITLE
Set Active Tab Dynamically

### ISSUE THREAD

**Issue by onecib** [bsgriggs/mendix-controllable-tab-container#5]
Hey there,

is it possible to set a given Tab to be active directly after loading the page dynamically ? 

Example: in a page containing 3 Tabs (Tab1, Tab2 and Tab3). Tab 1 is set as Active per Default. I want Tab3 to be the one Active.

PS: I am not aiming to change the tab sort .

Thanks in advance.

**Comment by bsgriggs** [comment]
Hi, you can use the 'Default Tab Index' expression to dynamically set the initial tab. You can either write an expression directly in the widget or pass in an integer from a non-persistent entity. 

Hope that helps!
